# Use Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /pythoncode

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Run app
CMD ["python", "main.py"]